# Generated by Django 4.2.4 on 2023-08-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
    ]
