# Generated by Django 4.2.4 on 2023-08-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
