# Generated by Django 4.2.4 on 2023-08-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='logo',
            field=models.ImageField(null=True, upload_to='blogs/images'),
        ),
    ]
