# Generated by Django 4.2.4 on 2023-08-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_blog_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='logo',
            field=models.ImageField(null=True, upload_to='blogs/images'),
        ),
    ]
